### PR TITLE
Add support for updating the root domain record

### PR DESCRIPTION
**Pull request by linuzer**
Let's say you have the domain 'example.com'. So there is a A-record for 'example.com' with the IP-address of the main server, e.g. serving www.example.com. Of course you could have further hosts like 'server1.example.com', which could be updated without problem.
But if you would like to use your script to update the A-record for 'example.com', the script fails for two reasons:

1. The function fetchzone_records _does_ usually return more than 1 result for the root domain, since there are usually all sorts of other DNS-recors, like SOA, TXT, MX, etc... So to fix this, I added a `type=A` to the query.
2. the $hostPart variable is empty in this case, leading to an API-error. To fix it, you have to use in this case the $domainPart as name, but followed by a "." to avoid renaming the record.

I made two more changes, that might be discussible:
1. I removed the logic to fetch the IP-address from the client request. The address returned by `$_SERVER['REMOTE_ADDR']` can be IPv4 or IPv6 - depending on the way the client connects to the server. So basically there needs to be done some kind of address-recognition. I'm planning to extend the script to also support IPv6 (that is update AAAA-records). 
2. I extended the return infos in two places to include the cPanel-side error messages to help debug any issues during setup (or later when something goes wrong...)

So I'm suggesting this PR to improve your script, which is really cool. I had a different one so far, but that was just far too complicated. I just like yours, it's simple, easy and just get's the job done.

Thanks for your work!

### CODE REVIEW

**Comment by raceybe** [comment]
I have no objection, but I'll engage in due diligence and review the commits just so I understand what changes are there. Is any existing functionality changed aside from updating return values in places?

**Comment by linuzer** [comment]
Only what I described above. So, at the moment yes, the feature to read the IP-address from `$_SERVER['REMOTE_ADDR']` when it is not provided via the parameter. But feel free to re-enable those lines for the time being. At the end a more sophisticated logic would be necessary to differentiate between IPv4 and IPv6.

**Comment by raceybe** [comment]
Cool, my main goal with the code was to support home routers and such that support basic DynDNS functionality, as long as you can supply an update url (I was using it with a Ubiquiti ER-X). I'm no programmer, so I'll merge, and hope that others continue to find it useful. Thanks!

**Comment by raceybe** [comment]
Oh, and as I haven't run this code for a while (I don't currently have it configured anywhere) can you give the documentation a once over and see if anything obvious changes based on what you did?

**Comment by linuzer** [comment]
This is also my use-case. I think there shouldn’t be a problem. If so, just tell me, I could have a look into it.
Yes, I can adapt the Readme a little bit, although there is basically anything on the user side that changed. But I’ll have a look..

**Comment by raceybe** [comment]
just letting you know I moved a bunch of the code around in an attempt to make it a little faster, and easier to work with. Your root domain changes should be intact, but I removed the IPv6 stuff since dyndns2 doesn't support it as far as I know. IPv6 can be added if more protocols are added.

**Pull request merged**
